spring:
  profiles:
    include:
      - aws  // application-aws.yml
cloud:
  aws:
    sqs:
      queue:
        url: https://sqs.ap-northeast-2.amazonaws.com/312531585294/sendy-training-sqs-queue
    region:
      static: ap-northeast-2
    credentials:
      instance-profile: true
    stack:
      auto: false